import numpy as np
import matplotlib.pyplot as plt
import os

# Path to the stats file generated by uncertainty_shells.py
STATS_PATH = "pipeline_rgb/shape/model_stage2/radial_stats.npz"
OUTPUT_IMG = "radial_uncertainty_plot.png"

def plot_radial_profile():
    if not os.path.exists(STATS_PATH):
        print(f"Error: Could not find {STATS_PATH}. Run uncertainty_shells.py first.")
        return

    # Load data
    data = np.load(STATS_PATH)
    # Mean radius and Standard Deviation
    mean_r = data["mean_r"]
    std_r = data["std_r"]
    
    # We collapse the elevation (phi) to get a 2D "Top-Down" view for the plot
    # Taking the middle slice (horizontal plane of the robot)
    mid_idx = mean_r.shape[1] // 2
    r_profile = mean_r[:, mid_idx]
    sigma_profile = std_r[:, mid_idx]
    
    # Angles (Theta)
    theta = np.linspace(0, 2*np.pi, len(r_profile))

    # Setup Polar Plot
    fig, ax = plt.subplots(subplot_kw={'projection': 'polar'}, figsize=(8, 8))
    
    # Plot Mean Shape (Blue)
    ax.plot(theta, r_profile, color='blue', linewidth=2, label='Mean Robot Shape')
    
    # Plot Safety Boundary (Mean + 3 Sigma) (Red)
    safety_r = r_profile + 3 * sigma_profile
    ax.plot(theta, safety_r, color='red', linewidth=2, linestyle='--', label='Safety Boundary (3σ)')
    
    # Fill the uncertainty gap
    ax.fill_between(theta, r_profile, safety_r, color='red', alpha=0.1)

    # Styling
    ax.set_title("Directional Radial Statistics (Top-Down View)", va='bottom', fontsize=14, fontweight='bold')
    ax.legend(loc='lower right', bbox_to_anchor=(1.1, -0.1))
    ax.grid(True, alpha=0.3)

    # Save
    plt.savefig(OUTPUT_IMG, dpi=300, bbox_inches='tight')
    print(f"Plot saved to {OUTPUT_IMG}")
    plt.close()

if __name__ == "__main__":
    plot_radial_profile()